-- ============================================================
-- 神戸立ち飲みマップ — 90店舗シードデータ
-- ソース: 食べログ81件 + Retty + Instagram + 神戸ジャーナル等
-- 更新: 2026-03-23
-- ============================================================
-- 実行前に restaurants テーブルが存在することを確認してください
-- ============================================================

insert into restaurants (
  name, area, category,
  budget_min, budget_max, budget_estimated,
  tachinomi_type, vibe_tags,
  instagram_handle, is_new_open, open_date,
  foreigner_friendly_score, solo_friendly_score, local_experience_score,
  priority_score, is_published, business_status,
  internal_notes, source
) values

-- ============================================================
-- 三宮エリア（60店）
-- ============================================================

('ライトスタンド', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'bar', ARRAY['local','casual','instagram','inbound-friendly'],
 'lightstand_kobe', false, null,
 3, 4, 4,
 85, true, 'OPERATIONAL',
 '元町筋通2・ビアザ近く。スタンディング居酒屋。Instagram活発で映えも◎。地元若者に人気。', 'manual'),

('ふみたち バー', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 5,
 80, true, 'OPERATIONAL',
 '三宮駅1分。立ち飲みバー。地元常連多め。', 'manual'),

('伊藤酒店', 'sannomiya', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 85, true, 'OPERATIONAL',
 '三宮駅2分。角打ちの老舗。¥500〜で飲める。一人客ウェルカム。神戸在住者なら絶対知ってる。Retty角打ち1位。', 'manual'),

('立ち火 Blend', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮駅2分。立ち飲みバー。', 'manual'),

('鮮家 風鶴', 'sannomiya', ARRAY['standing-bar','yakitori'],
 1500, 2000, false,
 'yakitori', ARRAY['local','yakitori','casual'],
 null, false, null,
 2, 4, 5,
 80, true, 'OPERATIONAL',
 '三宮市営駅35m。焼鳥立ち飲み。煙漂う本格焼鳥。', 'manual'),

('かぴぐら', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','meat','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮駅1分。北浜肉・ソーセージの立ち飲み。肉系好きに人気。', 'manual'),

('赤魚鮮場ちゃんと 三宮店', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮駅3分。', 'manual'),

('アザブバー', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'bar', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮駅2分。AZABU BAR。立ち飲みバー。', 'manual'),

('宇宙とやすらいでSAKABAとき', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual','unique'],
 null, false, null,
 2, 4, 5,
 82, true, 'OPERATIONAL',
 '1F立ち飲み＋2-3F座席。食べログTOP掲載。独特な雰囲気。', 'manual'),

('THE BAKE', 'sannomiya', ARRAY['standing-bar','wine'],
 1500, 2000, false,
 'wine', ARRAY['casual','wine','unique','date-ok'],
 null, false, null,
 3, 3, 3,
 80, true, 'OPERATIONAL',
 'パン×ワインの立ち飲み。昼・夜両方営業。インスタ映えする業態。', 'manual'),

('高羽', 'sannomiya', ARRAY['standing-bar','yakitori'],
 700, 1000, false,
 'yakitori', ARRAY['local','cheap','yakitori','authentic'],
 null, false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '三宮市営駅90m。串焼き立ち飲み。安くて旨い。一人客に最高。', 'manual'),

('4匹無 装 小店 ロエリア 東側店', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual','unique'],
 null, false, null,
 2, 3, 4,
 78, true, 'OPERATIONAL',
 '無国籍立ち飲み。', 'manual'),

('立ち呑み 京都会', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '三宮。¥1,000以下で飲める。一人客多い。', 'manual'),

('フレイク', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'bar', ARRAY['casual','beer','group-ok'],
 null, false, null,
 3, 3, 3,
 78, true, 'OPERATIONAL',
 '旧居留地285m。ビアホール系立ち飲み。', 'manual'),

('Uo魚', 'sannomiya', ARRAY['standing-bar','seafood'],
 700, 1000, false,
 'seafood', ARRAY['local','cheap','seafood','authentic'],
 null, false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '大丸前213m。海鮮立ち飲み。新鮮な魚介を格安で。地元漁師御用達感。', 'manual'),

('立ちびんの', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '旧居留地77m。', 'manual'),

('スタンド クラシック', 'sannomiya', ARRAY['standing-bar'],
 2000, 3000, false,
 'bar', ARRAY['casual','quality','date-ok'],
 null, false, null,
 3, 3, 3,
 60, true, 'OPERATIONAL',
 '三宮駅1分。少し高めだが品質高い立ち飲みバー。', 'manual'),

('立ち妙 サ', 'sannomiya', ARRAY['standing-bar','yakitori'],
 1500, 2000, false,
 'yakitori', ARRAY['local','yakitori','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮市営駅111m。串焼き立ち飲み。', 'manual'),

('ふとした屋', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮市営駅219m。', 'manual'),

('焼牛ちびちび クリ', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','meat','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '焼牛立ち飲み。肉系好きに。', 'manual'),

('立ち呑み ふぶけ', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','unique'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '燻製料理の立ち飲み。ユニークな一軒。', 'manual'),

('スタンド GONTa2', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '三宮駅2分。Retty掲載。', 'manual'),

('歌舞 ロッコン のどかの小屋 本店', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','unique','casual'],
 null, false, null,
 2, 3, 5,
 80, true, 'OPERATIONAL',
 'レゲエ立ち飲み。音楽好きの常連多め。個性的な空間。', 'manual'),

('スタンド サンジ', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮。', 'manual'),

('焼鳥くわまる', 'sannomiya', ARRAY['standing-bar','yakitori'],
 700, 1000, false,
 'yakitori', ARRAY['local','cheap','yakitori'],
 null, false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '旧居留地140m。安旨焼鳥。一人飲みの定番。', 'manual'),

('路地裏スタンド アンプク', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'bar', ARRAY['local','casual','instagram'],
 null, false, null,
 3, 4, 4,
 82, true, 'OPERATIONAL',
 '三宮駅1分。路地裏の隠れ家スタンド。Instagram有り。Retty・食べログ掲載。', 'manual'),

('スタンド Gonta', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '三宮。aumo掲載。', 'manual'),

('小寿々酒店', 'sannomiya', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '角打ち。老舗感ある酒屋立ち飲み。地元色強い。', 'manual'),

('神戸地鶏串焼き 鮮な屋 2号店', 'sannomiya', ARRAY['standing-bar','yakitori'],
 1000, 1500, false,
 'yakitori', ARRAY['local','yakitori','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '神戸地鶏専門の串焼き立ち飲み。2号店。', 'manual'),

('クインの上に渡って', 'sannomiya', ARRAY['standing-bar','wine'],
 1500, 2000, false,
 'wine', ARRAY['casual','wine','date-ok'],
 null, false, null,
 3, 3, 3,
 80, true, 'OPERATIONAL',
 'ワイン立ち飲み。ちょっとおしゃれな雰囲気。', 'manual'),

('スタンドフタコ', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','unique','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '珍しい動物系おつまみが特徴。個性派。', 'manual'),

('旨み 楽路', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '大丸前2分。旨立ち飲み。安くて旨い系。', 'manual'),

('GASTORONOMIA BUCO', 'sannomiya', ARRAY['standing-bar','italian'],
 1500, 2000, false,
 'italian', ARRAY['casual','italian','date-ok','unique'],
 null, false, null,
 3, 3, 3,
 82, true, 'OPERATIONAL',
 'イタリアン立ち飲み。三宮方面。ワインとイタリアン料理。デートにも。', 'manual'),

('ほその小屋', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','homestyle'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '家庭料理系立ち飲み。アットホームな雰囲気。', 'manual'),

('立ちみ 宍の菜', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮方面。', 'manual'),

('ムーン バイル', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'bar', ARRAY['casual','date-ok'],
 null, false, null,
 2, 3, 3,
 80, true, 'OPERATIONAL',
 '立ち飲みバー。', 'manual'),

('浮世本日本酒店 SANNOMIYA', 'sannomiya', ARRAY['standing-bar','sake-bar'],
 1500, 2000, false,
 'wine', ARRAY['local','sake','casual'],
 null, false, null,
 3, 4, 4,
 60, true, 'OPERATIONAL',
 '日本酒立ち飲み。日本酒好きに。Retty掲載。', 'manual'),

('ロエリア サルナゲ 洗礼組', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','unique','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 'タコス立ち飲み。ユニークな業態。', 'manual'),

('鶴亞拉窪', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 5, 5,
 78, true, 'OPERATIONAL',
 '三宮。ぐるなびネット掲載。', 'manual'),

('三十酒店 メルカーレ', 'sannomiya', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '紫の筋方面。角打ち。feel-kobe掲載。地元感強い。', 'manual'),

('立ち飲み ごっち', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual','instagram'],
 'gocchi_kobe', false, null,
 3, 4, 4,
 82, true, 'OPERATIONAL',
 '元町筋通1・カルメン近く。Instagram活発(@gocchi_kobe)。若者に人気。', 'manual'),

('立ち飲み ふたたち', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','instagram','lunch-ok'],
 null, false, null,
 2, 4, 4,
 82, true, 'OPERATIONAL',
 '元町筋通。昼飲み対応(12:30〜)。Instagram有。', 'manual'),

('立ち飲み 1', 'sannomiya', ARRAY['standing-bar','wine'],
 1500, 2000, false,
 'wine', ARRAY['casual','wine','instagram','new-open'],
 'tachinomi_1', true, '2025-10-01',
 3, 3, 3,
 84, true, 'OPERATIONAL',
 '旧居留地231m。日本馬酒×ワインの新業態。2025年10月OPEN。Instagram活発(@tachinomi_1)。食べログ新着。', 'manual'),

('立ちみ やっとこ', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','instagram'],
 '_yotteko_', false, null,
 3, 4, 4,
 82, true, 'OPERATIONAL',
 '三宮。Instagram(@_yotteko_)。', 'manual'),

('立ちみ妙 頂', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','late-night','instagram'],
 'stand_itadaki', false, null,
 2, 4, 4,
 82, true, 'OPERATIONAL',
 '加納町4(元町方面)。深夜営業 18:00〜27:00。Instagram(@stand_itadaki)。深夜飲みに最適。', 'manual'),

('立ち飲み屋台式 さんかく 三宮店', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','instagram'],
 'stand.sankaku', false, null,
 3, 4, 4,
 80, true, 'OPERATIONAL',
 '中山手通1。屋台式立ち飲み。チェーン系。Instagram(@stand.sankaku)。', 'manual'),

('立ちみ妙 風', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','instagram'],
 'tachinomi_fu_2023', false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮。平日17〜23/土日祝13〜23。Instagram(@tachinomi_fu_2023)。', 'manual'),

('立ち呑みニューワールド', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','instagram','new-open'],
 null, false, '2024-06-01',
 3, 4, 4,
 80, true, 'OPERATIONAL',
 '中山手通2。2024年6月OPEN。Instagram有。', 'manual'),

('Ready Steady Go!', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual','new-open'],
 null, true, '2026-03-05',
 3, 4, 3,
 85, true, 'OPERATIONAL',
 '旧居留地236m。2026年3月5日OPEN。食べログ最新店。まだ口コミ少ない分狙い目。', 'manual'),

('エビのスタンド', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '三宮駅1分。Retty掲載。', 'manual'),

('立ち呑み ふなちゃん', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 'ビアザ高架下。', 'manual'),

('立ちよせ酒場 魚天', 'sannomiya', ARRAY['standing-bar','seafood'],
 1000, 1500, false,
 'seafood', ARRAY['local','seafood','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 'ビアザ高架下。海鮮立ち飲み。', 'manual'),

('立ち呑み Zen', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 'ビアザ周辺。めちゃ飲み名鑑(2024/3OPEN)。', 'manual'),

('桜根', 'sannomiya', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 'ビアザ高架下。', 'manual'),

('スタンドアベ マリウリ', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 'ビアザ高架下。aumo掲載。', 'manual'),

('スタンドサンジ 2nd', 'sannomiya', ARRAY['standing-bar'],
 700, 1000, false,
 'tachinomi', ARRAY['local','cheap','casual','instagram'],
 'standsanji32z', false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '元町筋通1・ビアザ高架下。旧居留地西口1分。天神さん側にある。Instagram(@standsanji32z)。', 'manual'),

('竜 ヴァルハラ', 'sannomiya', ARRAY['standing-bar','yakitori'],
 1500, 2000, false,
 'yakitori', ARRAY['local','yakitori','instagram','meat'],
 'kobe_valhalla', false, null,
 2, 4, 4,
 82, true, 'OPERATIONAL',
 '元町筋通3・大丸前。希少部位の焼串＋生のサーモン串。Instagram(@kobe_valhalla)。', 'manual'),

('ホルモン 福寅', 'sannomiya', ARRAY['standing-bar','hormones'],
 1500, 2000, false,
 'hormones', ARRAY['local','meat','instagram','late-night'],
 'horumon_fukutora', false, null,
 2, 4, 5,
 82, true, 'OPERATIONAL',
 '二宮筋角飲食行。新鮮ホルモンを毎日18〜24時。Instagram(@horumon_fukutora)。', 'manual'),

('STAND COBE', 'sannomiya', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 3, 4, 4,
 80, true, 'OPERATIONAL',
 '旧居留地。平日17〜24/土日祝15〜24・火休み。', 'manual'),

('ジョージ', 'sannomiya', ARRAY['standing-bar','yakitori'],
 1500, 2000, false,
 'yakitori', ARRAY['local','yakitori','instagram','casual'],
 'jooji0725', false, null,
 2, 4, 4,
 82, true, 'OPERATIONAL',
 '元町筋通2。串焼きスタンド。18〜24時。Instagram(@jooji0725)。', 'manual'),

-- ============================================================
-- 元町・東京町エリア（15店）
-- ============================================================

('山下酒店', 'motomachi', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '元町(ビアザ周辺)。角打ち。神戸ジャーナル掲載。', 'manual'),

('赤松酒店', 'motomachi', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic','historic'],
 null, false, null,
 2, 5, 5,
 85, true, 'OPERATIONAL',
 '東京町路地裏。創業90年の老舗角打ち。神戸ジャーナル掲載。歴史を感じる空間。外国人も喜ぶ本物体験。', 'manual'),

('立ち飲み ふたたち 元町', 'motomachi', ARRAY['standing-bar'],
 1000, 1200, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '元町高架下。', 'manual'),

('お金の美術館 神戸元町店', 'motomachi', ARRAY['standing-bar'],
 1000, 1500, false,
 'bar', ARRAY['casual','unique','date-ok'],
 null, false, null,
 3, 3, 3,
 78, true, 'OPERATIONAL',
 '元町。立ち飲みバー。ユニークなコンセプト。', 'manual'),

('Moridini', 'motomachi', ARRAY['standing-bar','italian'],
 1500, 2000, false,
 'italian', ARRAY['casual','italian','new-open','date-ok'],
 null, true, '2025-08-01',
 3, 3, 3,
 83, true, 'OPERATIONAL',
 '元町付近。イタリアン立ち飲み。2025年8月OPEN。めちゃ飲み名鑑掲載。', 'manual'),

('昭和レゲエBAR ニューロッコン', 'motomachi', ARRAY['standing-bar'],
 1500, 2000, false,
 'bar', ARRAY['casual','unique','new-open','late-night'],
 null, true, '2026-03-01',
 2, 3, 4,
 85, true, 'OPERATIONAL',
 '元町付近。レゲエバー。2026年3月OPEN・最新店。めちゃ飲み名鑑掲載。独特の雰囲気。', 'manual'),

('家のくだ ひと', 'motomachi', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','new-open'],
 null, true, '2026-03-01',
 3, 4, 4,
 84, true, 'OPERATIONAL',
 '元町付近。屋台式/立ち飲み。2026年3月OPEN・最新店。めちゃ飲み名鑑掲載。', 'manual'),

('chotto', 'motomachi', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','new-open'],
 null, false, '2025-12-01',
 3, 4, 4,
 82, true, 'OPERATIONAL',
 '元町付近。2025年12月OPEN。めちゃ飲み名鑑掲載。', 'manual'),

('立ち呑み 稲田酒店', 'motomachi', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 82, true, 'OPERATIONAL',
 '元町。角打ち。Googleマップ検索。', 'manual'),

('イキいきなびき', 'motomachi', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 'ビアザ高架下。', 'manual'),

('元町ワイン食堂 カ・ヴォリア・ジュ', 'motomachi', ARRAY['standing-bar','wine'],
 1500, 2000, false,
 'wine', ARRAY['casual','wine','date-ok'],
 null, false, null,
 3, 3, 3,
 80, true, 'OPERATIONAL',
 '元町。ワイン立ち飲み食堂。Googleマップ検索。', 'manual'),

('角打ち 桃巻', 'motomachi', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '元町。角打ち。Googleマップ検索。', 'manual'),

('立ち飲み ほざ', 'motomachi', ARRAY['standing-bar'],
 800, 1200, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '元町。Googleマップ検索。', 'manual'),

('スタンド海', 'motomachi', ARRAY['standing-bar','seafood'],
 1000, 1500, false,
 'seafood', ARRAY['local','seafood','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '元町。海鮮立ち飲み。Googleマップ検索。', 'manual'),

('立ち飲み えっちゃん', 'motomachi', ARRAY['standing-bar'],
 800, 1200, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '元町。Googleマップ検索。', 'manual'),

-- ============================================================
-- 周辺エリア・新店（15店）
-- ============================================================

('濱田屋', 'surroundings', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic','historic'],
 null, false, null,
 2, 5, 5,
 60, true, 'OPERATIONAL',
 '魚崎。創業70年の老舗角打ち。feel-kobe掲載。電車で少し足を伸ばす価値あり。', 'manual'),

('かじか屋ふる店', 'surroundings', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '阪急沿線。角打ち。Retty掲載。', 'manual'),

('岡本方面 多幸湯地区', 'surroundings', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 60, true, 'OPERATIONAL',
 '多幸湯エリア。ぐるなび2位。', 'manual'),

('まさ 方川店', 'surroundings', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 60, true, 'OPERATIONAL',
 '方川。ぐるなび3位。', 'manual'),

('立ちみ 赤ひげ本店', 'surroundings', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '多幸湯。Retty多幸湯エリア1位。地元民の聖地。', 'manual'),

('岡田酒器類米小屋', 'surroundings', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 80, true, 'OPERATIONAL',
 '多幸湯。角打ち。Retty・角打ち特集掲載。', 'manual'),

('スタンドロビンフット', 'surroundings', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '多幸湯。Retty掲載。', 'manual'),

('はっくる', 'surroundings', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','new-open'],
 null, true, '2026-03-02',
 3, 4, 3,
 85, true, 'OPERATIONAL',
 '方川駅35m。2026年3月2日OPEN・最新店。食べログ新着。まだ未開拓感がある注目店。', 'manual'),

('にぎわいりん', 'surroundings', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual','new-open'],
 null, true, '2026-03-01',
 3, 4, 3,
 85, true, 'OPERATIONAL',
 '多幸湯駅213m。2026年3月OPEN・最新店。食べログ新着。', 'manual'),

('串とめし くろさき たかるお 三宮駅前店', 'surroundings', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual','new-open','unique'],
 null, true, '2026-02-05',
 3, 4, 3,
 86, true, 'OPERATIONAL',
 'さんロータ通り。2026年2月5日OPEN・注目次世代屋台式。串とめし業態。食べログ注目店。', 'manual'),

('謙食 sosai', 'surroundings', ARRAY['standing-bar'],
 1500, 2000, false,
 'tachinomi', ARRAY['local','casual','new-open','unique'],
 null, false, '2025-12-01',
 3, 4, 4,
 82, true, 'OPERATIONAL',
 '二宮。多国籍立ち飲み。2025年12月OPEN。神戸ジャーナル掲載。', 'manual'),

('立ち飲み 山子', 'surroundings', ARRAY['standing-bar'],
 1000, 1500, false,
 'tachinomi', ARRAY['local','casual'],
 null, false, null,
 2, 4, 4,
 80, true, 'OPERATIONAL',
 '東灘区。ローカル情報。', 'manual'),

('立ち飲み サカナ', 'surroundings', ARRAY['standing-bar','wine'],
 1000, 1500, false,
 'wine', ARRAY['local','wine','casual'],
 null, false, null,
 2, 4, 4,
 78, true, 'OPERATIONAL',
 '西宮。ワイン立ち飲み。ローカル情報。', 'manual'),

('立ち飲み 森', 'surroundings', ARRAY['standing-bar'],
 800, 1200, false,
 'tachinomi', ARRAY['local','cheap','casual'],
 null, false, null,
 2, 4, 4,
 78, true, 'OPERATIONAL',
 '灘区。ローカル情報。', 'manual'),

('角打ち ふなちゃん', 'surroundings', ARRAY['kakuuchi','standing-bar'],
 500, 1000, false,
 'kakuuchi', ARRAY['local','cheap','solo-friendly','authentic'],
 null, false, null,
 2, 5, 5,
 78, true, 'OPERATIONAL',
 '二宮。角打ち。ローカル情報。', 'manual');

-- ============================================================
-- 確認クエリ
-- ============================================================
-- select count(*), area from restaurants group by area;
-- select count(*) from restaurants where is_new_open = true;
-- select count(*) from restaurants where is_published = true;
